### ISSUE TITLE
Add support for CodeBuild cache

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/handel-codepipeline#100]
CodeBuild now supports caching out-of-the-box: https://aws.amazon.com/blogs/devops/how-to-enable-caching-for-aws-codebuild/ , and as of today, they've added support for the requisite pieces to the Node client.

I can spend some time working on this this week.  It shouldn't be too hard.

Here's what I'm thinking:

We create one account-wide Handel cache bucket. Each build project will have a different prefix (`{app}/{pipeline}/{phase}`). The config for each CodeBuild phase becomes really easy:

```yml
  type: codebuild
  cache: s3
```
Valid values would be 's3' or 'none' (the default), which match the API values of 'S3' and 'NONE'. We could theoretically use true/false, as I don't anticipate AWS adding another cache engine anytime soon, but we might want to make this be more future proof.

The actual files to be cached are defined in the buildspec, so we don't have to worry about it.

We could also utilize this same cache in some of the other codebuild-based phases (like Handel Deploy), which would reduce the amount of time it takes those phases to run.

**Comment by dsw88** [comment]
I'm super excited they've added caching now! Your proposal looks great. I do have a proposed modification to your proposal: Can we make the bucket a generic storage place for any of the phase types in Handel-CodePipeline instead of specific to caching?

Mostly I mean that this bucket would be named something like "handel-codepipeline-<region>-<accountId>", and if any other phase type in the future wants to have storage of some kind it would put it there.

I like the key prefix, but I would propose making sure the cache is further namespaced inside that key prefix with something like "codeBuildCache" just in case the CodeBuild phase ever has multiple needs for S3 storage. That may not be necessary, but it's an easy-enough thing to throw in to future-proof it in case we ever need to share that phase space with something else.

What do you think about these two things?

**Comment by ThatJoeMoore** [comment]
Yeah, that's a good idea. I'll be sure to add that extra level to the prefix.

**Comment by ThatJoeMoore** [comment]
We've already got a bucket we create for storing artifacts (`codepipeline-<region>-<account>`). I'm thinking we just reuse that?

**Comment by dsw88** [comment]
Ah yeah I forgot about that bucket, that's where the pipeline phase uploads go. That one sounds good to use.
